### ISSUE TITLE
header rendering

### ISSUE THREAD

**Issue by acthp** [carlosrocha/react-data-components#11]
I need custom header rendering. I patched it in here:

https://github.com/acthp/react-data-components/commit/fe11fdc346b05e5d8a5cd3d467f316bbabbb17f9

Would you want a pull request?

**Comment by aaronhayes** [comment]
+1 for pull request on this!

**Comment by votsa** [comment]
+1 But you probably don't need to make additional method for it.
Just need to change

`title: PropTypes.string.isRequired`

to be able to receive react component as a title without warnings so you would do something like this:

const columns = [
  {title:  <TitleComponent {...someProps} />, prop: 'name },
  ...
];
