### ISSUE TITLE
There is an error on sort function when sortByValues is undefined

### ISSUE THREAD

**Issue by khajonpot** [carlosrocha/react-data-components#25]
For my quick fixing:
function sort(sortByValues, data) {
  var sortedData = sortBy(data, sortByValues ? sortByValues.prop ? sortByValues.prop : '' : '' );
  if (sortByValues ? sortByValues.order ? sortByValues.order : '' : '' === 'descending') {
    sortedData.reverse();
  }
  return sortedData;
}

**Comment by DongShi** [comment]
I find the same problem.
I think it will be enough just 
//...
if (!sortByValues) {
    return data;
}

//do sort.

**Comment by carlosrocha** [comment]
This should no longer be an issue with the latest release.
