### ISSUE TITLE
How can I change onClick action for each row?

### ISSUE THREAD

**Issue by BesatZardosht** [carlosrocha/react-data-components#28]
I would like to change onClick (or on RowSelect?!!) action for the table, but how can I change it?

Thank you

**Comment by alecperkey** [comment]
I dont think this repo currently supports that. You could use the render function (see the example with google maps link) and just have one cell in the row return a button with your desired click handler. Maybe with some creative css it could be transparent and span the width of the table

**Comment by JD2k** [comment]
It is possible. You can add buildRowOptions to your Datatable tag. Like:
<DataTable
                    buildRowOptions={this.buildRowOptions}
                    ...someCode />

The method should look like this:

    buildRowOptions(row) {
        return {
            onClick: function(row) { <your code>}
        };
    }

**Comment by carlosrocha** [comment]
I added an example for this in the readme https://jsfiddle.net/carlosrocha/p9pouh1v/.
