### ISSUE TITLE
Way to disable pagination

### ISSUE THREAD

**Issue by kymtwyf** [carlosrocha/react-data-components#32]
Hi, 

I wonder whether it's configurable for pagination?

currentlyl, I am using it in this way 

```
initialData={this._getDataTableData()}
initialPageLength={this._getDataTableData().length}
```

thanks!

**Comment by carlosrocha** [comment]
I would like to move away from configuration properties and rely more on componentization, so I think the best solution for that is to create your own `DataTable` component, import `Table` and connect the actions, something like the render method in `PartialTable` but removing the `Pagination` component. Link to the relevant part: https://github.com/carlosrocha/react-data-components/blob/v1.0.1/src/PartialTable.js#L45
