### ISSUE TITLE
Is it possible to deactivate search field and/or pagination?

### ISSUE THREAD

**Issue by JD2k** [carlosrocha/react-data-components#34]
Hello,

i would like to know if and how it is possible to deactivate search field and/or pagination?

Thanks in advance

**Comment by carlosrocha** [comment]
I think at that point the only thing you need is the Table and connect the reducer, check out the options at [table prop types](https://github.com/carlosrocha/react-data-components/blob/master/src/Table.js#L43), example (not tested):

```jsx
import {Table, dataReducer, actions} from 'react-data-components';

export default SimpleTable extends Component {
  onSort = (value) => {
    this.setState((state) => dataReducer(state, actions.dataSort(value)));
  };

  render() {
    return (
      <Table
        columns={...}
        dataArray={this.state.data}
        onSort={this.onSort}
        sortBy={this.state.sortBy}
      />
    );
  }
}
```
