### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by RichardLindhout** [carlosrocha/react-data-components#36]
https://jsbin.com/ziyawu/9/edit?js,output

Gives:

2https://rawgit.com/carlosrocha/react-data-components/master/dist/react-data-components.min.js Failed to load resource: the server responded with a status of 404 ()
runner-3.39.14.min.js:1 ReferenceError: ReactDataComponents is not defined
    at ziyawu.js:1:828
ziyawu.js:37 Uncaught ReferenceError: ReactDataComponents is not defined

on Chrome browser OSX

**Comment by carlosrocha** [comment]
Thanks for the report, I just updated the examples to use jsfiddle: https://jsfiddle.net/carlosrocha/xgde4uh0/
