### ISSUE TITLE
Printing to page as well as export table content as CSV and PDF

### ISSUE THREAD

**Issue by bnlambert** [carlosrocha/react-data-components#40]
I enjoy the simplicity and yet powerful features of react-data-components. Great Job! 
I wish to know if it is possible to print or export table content into different format. I need some guidance on this.

Thanks

**Comment by carlosrocha** [comment]
Thank you! Exporting the table data is beyond the scope of this project, what I would probably do is something with https://github.com/d3/d3-dsv to create the data and something like this (http://stackoverflow.com/questions/3665115/create-a-file-in-memory-for-user-to-download-not-through-server) to make it available for the user.
