### ISSUE TITLE
Sorting is not case insensitive

### ISSUE THREAD

**Issue by gsheppard** [carlosrocha/react-data-components#7]
For my team's purposes, having case insensitive sorting is key. Currently the sorting groups items starting with a lower case letter separate from the rest of the items.

I was going to open a PR for this as well, but decided for an issue ticket because I wasn't sure how you would have wanted it implemented (whether this should be default functionality or an optional flag added when instantiating the DataTable).

**Comment by carlosrocha** [comment]
I would like to keep the API as simple as possible and focus more on the component side of things. I highly recommend that you adopt the Flux architecture, that way you have more control on the behavior of the sorting and fetching of data. I just updated the example to make it more simple:

https://github.com/carlosrocha/react-data-components/tree/master/example/flux

Hope that helps.
